### ISSUE TITLE
But does Hush accept or denies permission to site cookies?

### ISSUE THREAD

**Issue by elmimmo** [oblador/hush#10]
Just to be sure: so by not ever seeing the cookie permissions dialog, what am I de facto communicating:
* not accepting?
* accepting default values? (The default state for “legitimate interest” cookies in those alerts is usually “yes”)
* accepting all?

**Comment by oblador** [comment]
Hi!

Hush will block some specific scripts and hide some elements on the website, but can't and won't interact with the website itself and thus won't click on any buttons etc. I'm in EU so can only speak for our laws, but here the tracking/cookies are opt-in, meaning non-consent means not accepting. It's possible that some websites would adapt the behavior based on your geographical location, but I'd wager that most will go with the least common denominator and respect the GDPR laws everywhere. 

Hope that answers your concerns!
