### ISSUE TITLE
Breaks support.activision.com/privacy and amazon.jobs

### ISSUE THREAD

**Issue by najafmurtaza** [oblador/hush#103]
It is breaking https://support.activision.com/privacy and  https://amazon.jobs

**Comment by oblador** [comment]
Hi, how is it breaking amazon.jobs? Seems to work fine to me.

**Comment by najafmurtaza** [comment]
@oblador While filling out the application for the job it hides some button(s) on a step.

**Comment by oblador** [comment]
Should be fixed in latest version 👍
