### ISSUE TITLE
[Feature] Import feature

### ISSUE THREAD

**Issue by Laicure** [oblador/hush#109]
What about an _import_ feature so users have more control instead of the default filter?
Also, you'll have less issues regarding _Hush not blocking x ad on y site_.

That's like something Adguard has for content blocking: filter choices + custom imports.
The only problem would be parsing those.

**Comment by oblador** [comment]
That will add a lot of complexity to the app/UI and one of my design goals is for it to be extremely simple. I'm planning to add ability to permanently disable Hush for certain websites that are broken (it's already possible using built-in settings screen, but can be made more granular) via a share sheet action, but not something in the lines of what you're talking about.

**Comment by Laicure** [comment]
Oh, ok thanks for replying.

I just saw so many issues here regarding _x website not blocking ads_ and such.
So, it's like the filter source is being micro-managed.
I'm thinking, at least, adding those popular ad filters as sources (like fanboy, etc) instead of having one source?

Anyway, it's free as beer. Thanks for the app!
