### ISSUE TITLE
Breaks https://noyb.eu/en/project/cookie-banners

### ISSUE THREAD

**Issue by singingwolfboy** [oblador/hush#110]
Looks like Hush is auto-blocking any URL that contains "cookie-banner" in it. Unfortunately, that poses a problem for [this website](https://noyb.eu/en/project/cookie-banners), which is all about enforcing proper consent for cookie banners. Could you add an exception for this website?

**Comment by eproxus** [comment]
Also breaks this page https://noyb.eu/en/noyb-aims-end-cookie-banner-terror-and-issues-more-500-gdpr-complaints
