### ISSUE TITLE
Safari extension preference pane indicates Hush is not reading or transmitting content. Is this correct?

### ISSUE THREAD

**Issue by AgingKeeper** [oblador/hush#114]
I was having problems with a website and ended up needing to disable Hush & the content blocker extension I use in Safari on MacOS 11 to finally get it to work. I did not do anything to truly nail down if Hush was the source of my problem but I did notice that the Safari Preference pane for the Hush extension states -> "Hush" does not have permission to read or transmit content from any webpages. (screenshot attached I hope).  I have not looked at this pane closely until now but I would have expected Hush to read content from a web page to do its thing.  I can say that I rarely, if ever, get the annoying consent notices so I believe Hush is working.  Also, when I run the Hush app it indicates Hush is working.

I find the message to be confusing, if it is expected perhaps adding to the note the bolded text below "Block annoying cookie and tracking consent notices while keeping your privacy **and not requiring permission to read or transmit content from any webpages you visit**" 

<img width="522" alt="Screen Shot 2021-06-16 at 1 04 18 PM" src="https://user-images.githubusercontent.com/40922614/122277657-5d957880-cea3-11eb-9a10-2ec21c5b3374.png">

**Comment by ulbrich-media** [comment]
Hey, I'm not involved into the development of this App, but I think I can answer that. 

This is actually correct, Hush doesn't get any information about the websites you visit. Hush just generates a big list of Stuff to block (html classes to hide, urls to block). Safari uses that list to search for matches on the websites you visit. 

The reason why Hush may broke a Website you were visiting is, that some pages use additional Elements besides the Cookie Banners to enforce a consent, like e.g. a transparent background or disabling the scrolling. I guess it's quite hard to detect these little changes, so sometimes you need to disable Hush for that single page.

**Comment by oblador** [comment]
Like @ulbrich-media says, this is indeed correct, one of the selling points of Hush, and what makes it secure & fast.
