### ISSUE TITLE
Instructions slightly *too* simple

### ISSUE THREAD

**Issue by alexbird** [oblador/hush#12]
`Content Blockers` appears more than once in `Settings -> Safari`. Once in the `General` section and again in the `Settings For Websites` section. 

The first thing I did was skim quickly down to the latter, the first one I saw, but the wrong one!

**Comment by oblador** [comment]
It's a hard trade off, make the instructions too detailed and people don't read them, too sparse and they might not understand. I've actually tried it out on real humans and the current simple one worked best.

**Comment by alexbird** [comment]
I am a real human!

**Comment by alexbird** [comment]
Honest!

**Comment by oblador** [comment]
Haha, I'll need you to identify some traffic lights before I can believe it 😜

**Comment by Nicolapps** [comment]
I had the same issue, I was initially thinking that the installation didn’t work and I tried to reinstall the app several times. I didn’t know what to do until I saw this issue, so I would also suggest to be more precise 😀

**Comment by oblador** [comment]
In iOS 15 these are now having different names so I consider it being solved that way (new name is "Extensions").
