### ISSUE TITLE
Breaks covid19passbook.netlify.app

### ISSUE THREAD

**Issue by clawfire** [oblador/hush#121]
Some users of https://covid19passbook.netlify.app/ (which I made) reported on the last steps when we render a preview and inject it into the dom, thanks to mustache templating. Would require more cross-testing. 

If you don't have an EU digital covid certificate, you can click on "generate COSE" [on this page](https://dgc.a-sit.at/ehn/) to get a testing certificate to scan.

**Comment by oblador** [comment]
Hi, I'm unable to reproduce this, maybe you changed your markup?

**Comment by clawfire** [comment]
Oh yes sorry 😃 
So the thing is I had a div `#feedback` for getting the feedback of a scan (poor wording choice, I agree) and it was broken by hush (but not only). I changed the ID of the div and it worked 😃
