### ISSUE TITLE
block didomi's consent management platform 

### ISSUE THREAD

**Issue by sudoloic** [oblador/hush#125]
Hello!

Didomi (consent management platform) is used on several websites here in France. (see website allocine.fr for example)
It is not blocked by Hush.
I think it should be pretty easy to block it. Just needs : 
- to remove `#didomi-host` from DOM
- to remove `.didomi-popup-open` class from body

LMK if you need more info

Thanks :)

**Comment by oblador** [comment]
Hi, unfortunately the Safari block list API doesn't allow manipulation of the DOM in that way. Removing the body class is what's needed to undo the scroll blocker, but is not possible.
