### ISSUE TITLE
Makes k-rauta.se unusable

### ISSUE THREAD

**Issue by larkov** [oblador/hush#13]
When visiting https://www.k-rauta.se hush seems to block too much because it makes the site unusable. Unable to choose which store to visit for purchases and can't dismiss the "click & collect" banner at the top.

**Comment by oblador** [comment]
This is fixed on master, I'll submit a new version for review soon!

**Comment by oblador** [comment]
The new version is uploaded and waiting for review 👍

**Comment by larkov** [comment]
1.0.1 released 3 days ago on the mac app store still has the same problem with the site.

**Comment by oblador** [comment]
k-rauta is exempt and works well from what i can tell. Closing, open a new issue with reproduction steps if it persists in the latest version.
