### ISSUE TITLE
App hangs on 14.1

### ISSUE THREAD

**Issue by mbesemann** [oblador/hush#16]
Not sure if Hush requires a new version of iOS, but on 14.1 it just hangs on the splash screen.  Anything I can try to resolve this?

**EDIT:** Fixed by upgrading to 14.3 - trying to maintain jailbreakability ;)  However the minimum iOS version should probably be bumped up in the App Store listing.

**Comment by yslupdates** [comment]
Same issue here, I’m on 14.1 Xs Max

**Comment by BenXM** [comment]
Same issue using 14.1 on my iPad. It also doesn’t appear in my list of Content Blockers in Settings. Perhaps I should update iPadOS to 14.3?

**Comment by CoreKracker** [comment]
Same issue here.
App stuck's on start screen withe the logo. Nothing happends after that.
and it dosen't appear in the safari settings ( Content Blocker)
I'm also on iOS 14.1 (iPhone 12 Pro)
![Bildschirmfoto 2021-01-27 um 08 04 45](https://user-images.githubusercontent.com/52868009/105955362-73320f00-6076-11eb-9a1e-b132df58dd64.png)

**Comment by renetrial** [comment]
Works for me on iPhone with 14.4...
