### ISSUE TITLE
Won't install on MacOS 10.11

### ISSUE THREAD

**Issue by ebenhaber** [oblador/hush#17]
Hi,

Since Hush says that it is compatible with MacOS 10.11, I tried installing it on an old iMac running 10.11.6.

The Mac App Store downloads it, I click "Install", and it says:

We could not complete your purchase.

Hush can't be installed on "iMacInternal" because OS X version 11 or later is required"

Is there a work-around?

Thanks.

**Comment by oblador** [comment]
Unfortunately Hush requires macOS 11 as stated in the README and Mac App Store. There seems to be a bug in MAS where it sometimes wouldn't effectively block install attempts on older versions as reported in a different issue https://github.com/oblador/hush/issues/6#issuecomment-766188688.

**Comment by bobsica** [comment]
Thanks for doing this project. Any plans to support Catalina/Safari v14? I'd upvote that, many of us don't have that "extra mac" we can risk on putting buggy initial OS releases on.

**Comment by ebenhaber** [comment]
My apologies, I misread MacOS 11 as 10.11.
