### ISSUE TITLE
Some sites just stay grey, nowhere to click.

### ISSUE THREAD

**Issue by ds-jim** [oblador/hush#172]
Hello, 

This app has saved my sanity, thank you. 

I find some sites just grey out with nowhere to click for cookies but I can't dismiss the grey overlay. I just switch to Chrome or disable the app briefly but if there is a fix that'd be great. An example site is below;
 
https://www.smythstoys.com

**Comment by Globolo001** [comment]
Happens all over the web. The algorithm is imperfect. The dev doesn't seem to care enough (or doesn't have enough time) to add an exception list.

**Comment by ds-jim** [comment]
Understandable really, if it's not an unknown pattern then writing individual exceptions would be a nightmare.
