### ISSUE TITLE
google’s own cookies popup not blocked

### ISSUE THREAD

**Issue by TorsteinVin** [oblador/hush#21]
Google’s own popup asking to accept cookies from a norwegian ip address and norwegian system language on ios 14.1 and macOS 11.1 presents a popup asking to accept googles cookies. 

same with techcrunch.com presenting a popup about cookies written in norwegian language. 

Also, the producthunt page you're linking to on Hush's own webpage still shows the "sign up for our newsletter" popup, with Hush enabled.

im guessing its a localization issues and the rules in the app doesnt account for other system languages / webpage languages than  american english. 

other than that, thank your making this app. 

link that shows googles popup:
https://www.google.no/search?q=test&ie=UTF-8&oe=UTF-8&hl=nb-no&client=safari

ProductHunt popup
https://www.producthunt.com/posts/hush-for-safari?utm_source=badge-featured&utm_medium=badge&utm_souce=badge-hush-for-safari

**Comment by vitorgalvao** [comment]
[Seems like it might not be possible to support.](https://github.com/oblador/hush/issues/40#issuecomment-770469347)

**Comment by TorsteinVin** [comment]
Yeah, I saw that... too bad. I hope uBlock comes to Safari one day, as that blocker seems to be unstoppable.

**Comment by vitorgalvao** [comment]
> I hope uBlock comes to Safari one day

Unlikely. For that to happen, Apple itself would need to change.

> as that blocker seems to be unstoppable.

[It isn’t](https://github.com/uBlockOrigin/uBlock-issues/issues/338). There’s a good chance it will stop when major browsers abandon extension manifest v2.

**Comment by oblador** [comment]
Yeah not possible to block as it stands today. Closing for now!
