### ISSUE TITLE
"Hamburger" menu is being blocked on few websites (generic Elementor dialogs blocked)

### ISSUE THREAD

**Issue by operatino** [oblador/hush#25]
Hey,

Thanks a lot for a great app! I'll try to contribute myself with code, once have time learning how the extension works, but meanwhile hope this report will be useful. I've installed the extension yesterday, and noticed on 2 websites, that a commonly used pattern with hidden menu (opened with a hamburger icon button) is not working on mobile devices (narrow screen).

I could reproduce it both on desktop and iOS Safari. I found that the extension is injecting a big CSS selector with somehow forced highest specificity, and in this case, it's `.elementor-popup-modal.dialog-widget` selector that's blocking the mobile menu. It looks like the selector is too generic, and blocks some standard classnames from a library component (actually a [wordpress site builder](https://elementor.com/)), that could be used for virtually any dialogs, not only cookies.

One of the websites I've noticed this on is https://protosmanagement.com (the other website is behind auth).

Hope you will consider removing this generic popup selector, as I imagine it will block a variety of functional popups across many wordpress websites.

**Comment by oblador** [comment]
This should be fixed by #82
