### ISSUE TITLE
Why are there still ads? All ads should be blocked, no exceptions.

### ISSUE THREAD

**Issue by rrn21833** [oblador/hush#253]

**Comment by oblador** [comment]
It's not an adblocker

**Comment by rrn21833** [comment]
Ads are annoying.

Joel Arvidsson ***@***.***>于2023年8月25日 周五13:48写道：

**Comment by oblador** [comment]
Then use an adblocker? Ads pay for the websites you are using and I personally don't want to rob them of their income. You are free to do so.
