### ISSUE TITLE
[Workaround / Idea] Automatically click "Reject All" for Google Search in Private (anonymous) Browsing

### ISSUE THREAD

**Issue by neooleg** [oblador/hush#264]
Hi @oblador, thanks you for such a great product — hush!

# Problem

According to the following issues — it seems there no strait forward way to handle Google's cookie banner as other banners w/o broking website:
- https://github.com/oblador/hush/issues/223
- https://github.com/oblador/hush/issues/21

# Suggested Solution

What if:

1.  Find the "Reject All" button by XPath (IDs, classes might be dynamic, but the following XPath should remain constant):

<img width="1107" alt="image" src="https://github.com/oblador/hush/assets/1647049/5e0820fb-40bd-4ed9-85d1-40df577375b7">

2. Click this button with code like:

```javascript
document.getElementById('{button-id-found-by-xpath}').click();
``` 

@oblador, what do you think — might this work?

**Comment by oblador** [comment]
Hi, this won't work while also being 100% private as this extension aims to be. Any extension that does this could in theory track your browsing and obtain CC details etc, and would also by definition be slower. I know the tradeoffs, but for me personally I this is one of the main selling points, and there are a bunch of other alternatives that do the opposite for those that prioritise differently. Hope you understand! 👍

**Comment by neooleg** [comment]
Hi Joel,

I do understand and appreciate your response with such detail and the
reasoning behind it 🙌

Best regards,

*Oleg V.*
