### ISSUE TITLE
Do I need to keep Hush open on my Mac or can I close it

### ISSUE THREAD

**Issue by Lizard555** [oblador/hush#267]
Hi,

Probably a stupid question, but does Hush app need to run (have a dot under it in the dock) to work, or can I quit it?

Thanks,
Jan

**Comment by lukefernandez** [comment]
It does not need to be open with a dot under it in the dock to work. 
Enable it in your safari settings, and you should be good to go!
<img width="774" alt="Screenshot 2023-12-01 at 8 42 32 AM" src="https://github.com/oblador/hush/assets/8265202/b4914df7-a824-44a4-bf21-cd00f0e65ee1">

**Comment by lukefernandez** [comment]
@Lizard555, hopefully that should get you unstuck. Can you close this issue if it helped?

**Comment by NguyenCuong17012021** [comment]
help me close hus silent program. I did not receive the account security warning, thank you
