### ISSUE TITLE
What's the state of this safari extension?

### ISSUE THREAD

**Issue by nervenes** [oblador/hush#288]
Is Hush maintained and kept up to date? Last commit seems to be 7 months ago, last app store update was pushed 6 months ago. Are there any forks that's maintained that could be suggested?

**Comment by oblador** [comment]
There's now a new version available.

**Comment by nervenes** [comment]
thanks for keeping the extension up to date @oblador ! 🙏

are the new updates closed source? as i cannot see the changes in this repository.

**Comment by oblador** [comment]
I build and release locally, forgot to push latest changes – done now!
