### ISSUE TITLE
Latest update broke YouTube

### ISSUE THREAD

**Issue by drnixon** [oblador/hush#293]
After iOS 18 update, I saw a pending update to Hush. After installing, YouTube videos stopped playing. Clicking play did nothing. Disabling Hush corrected this. Not sure if an issue with Hush specifically or if it’s a conflict due to another installed content blocker (Stop the Madness Pro), but nothing would play until Hush was disabled.

**Comment by oblador** [comment]
Hi, on my iPhone 16 Pro on iOS 18 with just Hush installed it plays just fine. Could you try disabling the other extension?

**Comment by drnixon** [comment]
Weird, disabling all extensions except Hush made things work, re-enabling all other extensions did not stop it from working. Guess whatever was happening on my end was a momentary glitch?
