### ISSUE TITLE
Specific issue with The Guardian website

### ISSUE THREAD

**Issue by Superbuddha** [oblador/hush#296]
When activated, Hush locks scrolling on all pages of The Guardian. It's a problem encountered on several iPads with the latest version of iPadOs and Hush. Could you please solve this?

Many thanks.

**Comment by oblador** [comment]
Fixed by https://github.com/oblador/hush/pull/301

**Comment by Superbuddha** [comment]
Fix seemed to have worked at first but same issue is happening again. It's also affecting DW.com.
