### ISSUE TITLE
App doesn’t open 

### ISSUE THREAD

**Issue by DragonCat4012** [oblador/hush#45]
The app doesn’t open, it only shows the logo, and I don’t have an option to enable content blockers in my settings. The App Store says you need iOS version 14 or higher. My phone is on iOS 14 ;-;

**Comment by MalbecsDad** [comment]
Same issue here under iOS 14.1, iPhone 12 mini. App launches, but only displays logo, does not progress to screen showing “hush is enabled”

**Comment by MalbecsDad** [comment]
Confirmed update to iOS 14.4.1 has resolved the issue

**Comment by DragonCat4012** [comment]
same
