### ISSUE TITLE
Doesn't block cookie overlay on theguardian.com

### ISSUE THREAD

**Issue by acroamatic** [oblador/hush#47]
The support Guardian overlay is also not blocked.

**Comment by mitthrawnuruodo** [comment]
Didn't block cookie overlay (covering half the page) on https://www.theguardian.com/international today

**Comment by abilops** [comment]
Hush is able to properly block the cookie consent overlay, but then the page becomes unscrollable. As far I have noticed, it is only a problem with theguardian.com.
