### ISSUE TITLE
Super hard to read White on Yellow text.

### ISSUE THREAD

**Issue by MichaelQ** [oblador/hush#5]
Hey there.

Just installed Hush because @gruber. Looking forward to using it, thanks.

Found the White text on Yellow background super hard to read though.

Running iPadOS 14.4 on 2020 iPad Pro in dark mode.

Cheers

Michael
![AFF1A31B-FA68-485E-AD74-1CC7B080E226](https://user-images.githubusercontent.com/4957798/105612586-44ffc580-5e11-11eb-9a58-e3206a745f96.png)

**Comment by oblador** [comment]
Thanks for reporting! The latest stable version is 14.3 and this is how it looks on my iPad running that version:
![IMG_05F4E4F578D3-1](https://user-images.githubusercontent.com/378279/105612735-1f959c00-5dbe-11eb-9a85-9e5eef97d3eb.jpeg)

Are you running a beta or release candidate? It seems to be a bug with iPad OS itself.

**Comment by MichaelQ** [comment]
I am running the Public Beta profile but I believe the 14.4 update we got yesterday was a Release Candidate. Ver 18D52.

I switched to Light Mode and the text switched to Black (on Yellow).

Interesting I have Yellow background and yours is Black?

Light mode:
![CEC3A251-D28E-4CF1-B462-2C1A04DFC5BC](https://user-images.githubusercontent.com/4957798/105614944-d6c2ff00-5e20-11eb-9755-38719234ffcc.png)

**Comment by MichaelQ** [comment]
Same result on iPhone running 14.3 Public Bets 18c66. 
![030BD65B-7770-4204-B630-E0B3C6433D2C](https://user-images.githubusercontent.com/4957798/105615076-e42cb900-5e21-11eb-979d-5614e90771c1.png)
![0D1FEF49-714D-4155-8C13-E5A716EBAAD2](https://user-images.githubusercontent.com/4957798/105615077-e858d680-5e21-11eb-9889-90867a1d4c3a.png)

**Comment by oblador** [comment]
I upgraded to latest 14.4 RC, but also that renders fine on my iPad. I wonder if it's something specific to your device. Do you have any specific accessibility settings enabled that could cause this?

**Comment by oblador** [comment]
I have a potential fix waiting for review by the App Store. I'm not too confident though, it's hard to fix without being able to reproduce it.

**Comment by rizwankce** [comment]
I just downloaded the app and I had the same issue. The issue happens because of "increased contrast" a11y setting. If you enable it - you can reproduce on your end. @oblador 

![image](https://user-images.githubusercontent.com/12063704/105667009-90dd6800-5f00-11eb-99ba-c6e987530aef.png)

**Comment by hteumeuleu** [comment]
I also have this problem. I'm on an iPhone SE (1st gen), dark mode, and also happen to have the "Increase contrast" setting on.
