### ISSUE TITLE
Support for macOS Catalina

### ISSUE THREAD

**Issue by justdfd** [oblador/hush#6]
The MAS won't let me download this. Any chance you could provide support for macOS 10.15? At least 10.15.7? Or is this mostly a UIKit app?

**Comment by oblador** [comment]
I made this project partly as an excuse to check out the new Swift UI features launched with Big Sur knowingly that would exclude Catalina support. Big Sur has been out a while and I don't have plans to add it right now. 

Just trying to understand your situation, what's preventing you from upgrading? Backwards IT department?

**Comment by panckreous** [comment]
Not OP but personally, I have Big Sur running on my m1 because I have to. I dislike so much about it that upgrading my main dev machine from Catalina would only add negatives so I'm hoping to avoid until at least a point release that keeps everything par.

**Comment by JohnBlackburne** [comment]
I'm here for the same reason. I can't upgrade as my Mac, a late 2012 Mac mini, doesn't support Big Sur. Did think I could try pulling it and building it myself but if it's written using Big Sur specific features that's not going to work.

**Comment by justdfd** [comment]
Just personal preference. I actually avoided Catalina until last May 2020, when my new Mac arrived with it. (And upgrading to it on my old MacBook Pro involved 3 hours with Apple support due to a corrupt download.)

I've heard both good and bad about Big Sur. And no problems. 

(1) I moved away from SwiftUI over a year ago because of missing pieces... namely UIActivityViewController, UIImagePickerController, and most of all support for either MTKView or GLKView. But I'm also curious about both Catalyst and how my iOS apps may work in Big Sur. But I also opted out of automatically having them in the MAS.

(2) I use other ad blockers in Safari, and wanted to check out yours'. Oddly enough, when viewing the app page in this Catalina Mac it - at first - says it's compatible with it. But the dropdown (and download) says that macOS 11.0 is required. That's not on you, that's on Apple.

Forgive me for my oringal comment and asking about UIKit pieces. My bad. Do you think a Catalina build could be done using Catalyst? I'd be willing to give it a shot. In case you didn't know, John Gruber (Daring Fireball) posted about this project - but never mentioned anything about macOS minimum requirements. I'm guessing that's how others have heard about this.
