### ISSUE TITLE
Doesn't work on focus.de

### ISSUE THREAD

**Issue by sebastianlohmann** [oblador/hush#65]
See [https://www.focus.de/digital/videos/hilfe-fuers-smartphone-ihr-iphone-geht-bei-kaelte-in-die-knie-dann-muessen-sie-diesen-tasten-trick-unbedingt-kennen_id_6547102.html](https://www.focus.de/digital/videos/hilfe-fuers-smartphone-ihr-iphone-geht-bei-kaelte-in-die-knie-dann-muessen-sie-diesen-tasten-trick-unbedingt-kennen_id_6547102.html)

**Comment by oblador** [comment]
Hi, I'm unable to reproduce – what is not working?

**Comment by oblador** [comment]
Closing due to lack of replies.
