### ISSUE TITLE
Cookie notice on Change.org is not blocked

### ISSUE THREAD

**Issue by gracjankn** [oblador/hush#67]
![iPhone](https://user-images.githubusercontent.com/60069149/107646139-eabc8c80-6c79-11eb-9c1f-725b839e1171.jpg)
![MacBook](https://user-images.githubusercontent.com/60069149/107646144-ec865000-6c79-11eb-8f4c-9cc75667197e.png)

**Comment by oblador** [comment]
Unfortunately this one is not possible to block with Safari without also breaking the site.
