### ISSUE TITLE
BBC iPlayer

### ISSUE THREAD

**Issue by mattwood87** [oblador/hush#68]
The extension makes BBC iPlayer non-functional. I can browse for shows but when I hit the play button nothing happens. disabling hush allows it to work again.

The url is www.bbc.co.uk/iplayer

Thank you for this great tool!

**Comment by mloughran** [comment]
I also noticed this. The following JavaScript errors are raised only when Hush is enabled:

* `Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 't.cookiesEnabled')`
* `TypeError: undefined is not an object (evaluating 'window.bbccookies.readPolicy')`
