### ISSUE TITLE
Cookie notice on www.orange.pl is not blocked

### ISSUE THREAD

**Issue by gracjankn** [oblador/hush#69]
![iOS](https://user-images.githubusercontent.com/60069149/108054995-ac471900-704f-11eb-9636-4006fe1ff474.png)
![macOS](https://user-images.githubusercontent.com/60069149/108055003-aea97300-704f-11eb-8dda-a00d289c3326.png)

**Comment by oblador** [comment]
Thanks for reporting! Unfortunately the markup is obfuscated so even if I block it now, it will probably be unblocked by the next change on their end – so will not attempt unfortunately!
