### ISSUE TITLE
Not blocking "OneTrust" cookie nags on iOS?

### ISSUE THREAD

**Issue by tconkling** [oblador/hush#8]
I just installed and enabled Hush on iOS and visited https://rockpapershotgun.com, and it popped up a OneTrust cookie nag:

![IMG_360FF0CBDF9A-1](https://user-images.githubusercontent.com/709022/105616173-cf044b80-5d89-11eb-883e-30d403306c86.jpeg)

I tried disabling my other content blocker ("Purify"), and force-quit and relaunched Safari, but the popup still appeared. Is it possible I'm doing something wrong?

**Comment by lyptt** [comment]
Reproduced this on desktop too

**Comment by oblador** [comment]
Thanks for reporting, rockpapershotgun.com is specifically excluded to avoid breaking the site.

**Comment by lambertsson** [comment]
Deleting the onetrust element or styling it to be hidden does not seem to break the site from my testing..?

**Comment by abstractpenguin** [comment]
Created a PR https://github.com/oblador/hush/pull/44. I haven't noticed it breaking the site, but YMMV.

**Comment by oblador** [comment]
Should work in 1.0.3 that has been submitted for review.
