### ISSUE TITLE
Vimeo.com slow or broken when Hush is enabled

### ISSUE THREAD

**Issue by reefdog** [oblador/hush#93]
When visiting Vimeo.com in Safari with Hush enabled (and all other extensions disabled, to isolate Hush), Vimeo often doesn't seem to load page content; the page title appears atop the tab, but the page is completely blank. Periodically page content _does_ load, but after a long time. There aren't helpful console errors.

It's possible/probable this is the fault of something Vimeo is doing poorly and that Hush is behaving as designed, and/or this may be closed like #79, but I'm reporting it anyway (1) in case something can be done Hush-side, and (2) so that it's discoverable when people search Issues to see if Vimeo problems have already been reported.

macOS: 11.2.3
Safari: 14.0.3
Hush: 1.0.3

(Side note: 🙏 for an amazing extension/project!)

**Comment by oblador** [comment]
Is this problem persisting in the latest version? Seems to work fine for me.

**Comment by reefdog** [comment]
I'm not currently seeing it on:

macOS: 11.4
Safari: 14.1.1
Hush: 1.0.4

Unsure which, if any, of those changed to resolve this, or if the gremlins just exorcised themselves. :pray:
