### ISSUE TITLE
Breaks Intigriti.com navigation

### ISSUE THREAD

**Issue by hazcod** [oblador/hush#95]
Hi!

Enabling Hush disables the top navigation bar for https://www.intigriti.com/

![image](https://user-images.githubusercontent.com/5222512/116218958-5b3c5b00-a74b-11eb-8c02-fd8fc3b51e35.png)

![image](https://user-images.githubusercontent.com/5222512/116218993-65f6f000-a74b-11eb-90d7-16afba6d7b75.png)

**Comment by oblador** [comment]
Works for me in 1.0.5 that I just released for macOS, pending review on iOS.
