### ISSUE TITLE
Ineffective against Webedia group popups

### ISSUE THREAD

**Issue by Ozwel** [oblador/hush#98]
Hi,
In France a lot of huge websites are owned by a company named Webedia. For a few weeks now they are asking 2 EUR if you wish to refuse the cookies. Of course everyone goes back and select accept...

The popup is huge moreover.

You can check on several websites from Safari on iOS e.g.:
- https://www.allocine.fr/
- https://www.jeuxvideo.com/

Could you please have a have a look and check how to get rid of these despicable consent popups?

Many, many thanks.

**Comment by oblador** [comment]
Hi, 

I've looked into this and it's possible to block, but that will at the same time disable functionality on the website such as video players that simply won't start until cookies are accepted. So unfortunately I'll have to leave it unblocked for now.
